#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

if test "$HOSTNAME" = 'laika'; then
	# scale up so I can read this tiny screen!
	xrandr --dpi 144 # 150%
	#xrandr --dpi 192 # 200%
elif test "$HOSTNAME" = 'nessie'; then
	echo "Hello! I am $HOSTNAME" > /tmp/hidpi
else
	echo "~/.xinitrc doesn't have a DPI setting for $HOSTNAME" > /tmp/hidpi
fi

compton -CGb
# sh ~/.fehbg &
export TERMINAL=termite

# start the ssh-agent so I don't need to enter in a passphrase every time
eval $(ssh-agent)

# exec awesome
exec i3

